'use client';

import { useEffect, useState, useMemo } from 'react';
import Link from 'next/link';
import { api, OrderSummaryGlobal } from '@/lib/api';

/* ── Status config ───────────────────────────────── */

const STATUS_CONFIG: Record<string, { accent: string; bg: string; border: string; color: string; label: string }> = {
  draft:           { accent: '#8C8984', bg: 'rgba(0,0,0,0.04)',      border: 'rgba(0,0,0,0.09)',      color: '#8C8984', label: 'Unpaid' },
  submitted:       { accent: '#3850be', bg: 'rgba(56,80,190,0.06)',  border: 'rgba(56,80,190,0.15)',  color: '#3850be', label: 'Submitted' },
  paid:            { accent: 'var(--green)', bg: 'var(--green-dim)', border: 'var(--green-border)',   color: 'var(--green)', label: 'Paid' },
  split_to_brands: { accent: 'var(--gold)',  bg: 'rgba(158,124,63,0.06)', border: 'rgba(158,124,63,0.15)', color: 'var(--gold)', label: 'Processing' },
  closed:          { accent: '#555',    bg: 'rgba(0,0,0,0.03)',      border: 'rgba(0,0,0,0.08)',      color: '#555', label: 'Closed' },
};

type FilterTab = 'all' | 'unpaid' | 'paid' | 'processing' | 'closed';

const FILTER_MAP: Record<FilterTab, string[]> = {
  all: [],
  unpaid: ['draft', 'submitted'],
  paid: ['paid'],
  processing: ['split_to_brands'],
  closed: ['closed'],
};

/* ── Helpers ─────────────────────────────────────── */

function formatPrice(price: number | null) {
  if (price == null) return '—';
  return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', minimumFractionDigits: 0 }).format(price);
}

function formatDate(iso: string) {
  return new Date(iso).toLocaleDateString('en-US', { day: 'numeric', month: 'short', year: 'numeric' });
}

function timeAgo(iso: string) {
  const diff = Date.now() - new Date(iso).getTime();
  const mins = Math.floor(diff / 60000);
  if (mins < 60) return `${mins}m ago`;
  const hrs = Math.floor(mins / 60);
  if (hrs < 24) return `${hrs}h ago`;
  const days = Math.floor(hrs / 24);
  if (days < 7) return `${days}d ago`;
  return formatDate(iso);
}

/* ── Invoice download ────────────────────────────── */

function downloadInvoice(order: OrderSummaryGlobal) {
  const lines = [
    'INVOICE',
    '═══════════════════════════════════════',
    '',
    `Order ID:    #${order.id.slice(0, 8)}`,
    `Date:        ${formatDate(order.createdAt)}`,
    `Status:      ${STATUS_CONFIG[order.status]?.label ?? order.status}`,
    '',
    `Project:     ${order.project?.name ?? '—'}`,
    `Client:      ${order.project?.client?.name ?? '—'}`,
    '',
    `Items:       ${order._count.lineItems}`,
    `Brand POs:   ${order._count.brandPOs}`,
    '',
    '───────────────────────────────────────',
    `TOTAL:       ${formatPrice(order.totalAmount)}`,
    '───────────────────────────────────────',
    '',
    'Generated by Tradeliv',
    `${new Date().toISOString()}`,
  ];
  const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `invoice-${order.id.slice(0, 8)}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

/* ══════════════════════════════════════════════════════
   Orders Page
   ══════════════════════════════════════════════════════ */

export default function OrdersPage() {
  const [orders, setOrders] = useState<OrderSummaryGlobal[]>([]);
  const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState<FilterTab>('all');
  const [search, setSearch] = useState('');
  const [hoveredOrder, setHoveredOrder] = useState<string | null>(null);
  const [hoveredTab, setHoveredTab] = useState<FilterTab | null>(null);

  useEffect(() => {
    api.getAllOrders().then((r) => {
      if (r.data) setOrders(r.data);
      setLoading(false);
    });
  }, []);

  /* ── Derived data ──────────────────────────────── */

  const stats = useMemo(() => {
    const total = orders.reduce((sum, o) => sum + (o.totalAmount ?? 0), 0);
    const paidTotal = orders.filter(o => o.status === 'paid' || o.status === 'split_to_brands' || o.status === 'closed')
      .reduce((sum, o) => sum + (o.totalAmount ?? 0), 0);
    const unpaidTotal = orders.filter(o => o.status === 'draft' || o.status === 'submitted')
      .reduce((sum, o) => sum + (o.totalAmount ?? 0), 0);
    const paidCount = orders.filter(o => o.status === 'paid' || o.status === 'split_to_brands' || o.status === 'closed').length;
    const unpaidCount = orders.filter(o => o.status === 'draft' || o.status === 'submitted').length;
    return { total, paidTotal, unpaidTotal, paidCount, unpaidCount, count: orders.length };
  }, [orders]);

  const tabCounts = useMemo(() => ({
    all: orders.length,
    unpaid: orders.filter(o => o.status === 'draft' || o.status === 'submitted').length,
    paid: orders.filter(o => o.status === 'paid').length,
    processing: orders.filter(o => o.status === 'split_to_brands').length,
    closed: orders.filter(o => o.status === 'closed').length,
  }), [orders]);

  const filteredOrders = useMemo(() => {
    let result = orders;
    if (activeTab !== 'all') {
      const statuses = FILTER_MAP[activeTab];
      result = result.filter(o => statuses.includes(o.status));
    }
    if (search.trim()) {
      const q = search.toLowerCase();
      result = result.filter(o =>
        o.id.toLowerCase().includes(q) ||
        o.project?.name?.toLowerCase().includes(q) ||
        o.project?.client?.name?.toLowerCase().includes(q)
      );
    }
    return result;
  }, [orders, activeTab, search]);

  /* ── Tabs config ───────────────────────────────── */

  const tabs: { key: FilterTab; label: string }[] = [
    { key: 'all', label: 'All Orders' },
    { key: 'unpaid', label: 'Unpaid' },
    { key: 'paid', label: 'Paid' },
    { key: 'processing', label: 'Processing' },
    { key: 'closed', label: 'Closed' },
  ];

  /* ── Render ────────────────────────────────────── */

  return (
    <div style={{ padding: '32px 44px', maxWidth: 1100 }}>

      {/* Header */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 24 }}>
        <div>
          <h1 style={{ fontSize: 22, fontWeight: 800, color: 'var(--text-primary)', margin: 0, letterSpacing: '-0.02em' }}>Orders</h1>
          {!loading && (
            <p style={{ fontSize: 13, color: 'var(--text-muted)', marginTop: 4, margin: '4px 0 0' }}>
              {stats.count} order{stats.count !== 1 ? 's' : ''} across all projects
            </p>
          )}
        </div>
      </div>

      {/* Stats Cards */}
      {!loading && orders.length > 0 && (
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 12, marginBottom: 24 }}>
          <div className="card" style={{ padding: '14px 18px' }}>
            <div style={{ fontSize: 11, fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.5px', marginBottom: 6 }}>Total Value</div>
            <div style={{ fontSize: 20, fontWeight: 800, color: 'var(--text-primary)', letterSpacing: '-0.02em' }}>{formatPrice(stats.total)}</div>
          </div>
          <div className="card" style={{ padding: '14px 18px' }}>
            <div style={{ fontSize: 11, fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.5px', marginBottom: 6 }}>Collected</div>
            <div style={{ display: 'flex', alignItems: 'baseline', gap: 6 }}>
              <div style={{ fontSize: 20, fontWeight: 800, color: 'var(--green)', letterSpacing: '-0.02em' }}>{formatPrice(stats.paidTotal)}</div>
            </div>
          </div>
          <div className="card" style={{ padding: '14px 18px' }}>
            <div style={{ fontSize: 11, fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.5px', marginBottom: 6 }}>Outstanding</div>
            <div style={{ display: 'flex', alignItems: 'baseline', gap: 6 }}>
              <div style={{ fontSize: 20, fontWeight: 800, color: stats.unpaidCount > 0 ? '#3850be' : 'var(--text-muted)', letterSpacing: '-0.02em' }}>{formatPrice(stats.unpaidTotal)}</div>
            </div>
          </div>
          <div className="card" style={{ padding: '14px 18px' }}>
            <div style={{ fontSize: 11, fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.5px', marginBottom: 6 }}>Avg. Order</div>
            <div style={{ fontSize: 20, fontWeight: 800, color: 'var(--text-primary)', letterSpacing: '-0.02em' }}>
              {stats.count > 0 ? formatPrice(stats.total / stats.count) : '—'}
            </div>
          </div>
        </div>
      )}

      {/* Filter Tabs + Search */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 16, marginBottom: 20, borderBottom: '1px solid var(--border)', paddingBottom: 0 }}>
        <div style={{ display: 'flex', gap: 2 }}>
          {tabs.map((tab) => {
            const isActive = activeTab === tab.key;
            const isHovered = hoveredTab === tab.key;
            const count = tabCounts[tab.key];
            return (
              <button
                key={tab.key}
                onClick={() => setActiveTab(tab.key)}
                onMouseEnter={() => setHoveredTab(tab.key)}
                onMouseLeave={() => setHoveredTab(null)}
                style={{
                  padding: '8px 14px',
                  fontSize: 12.5,
                  fontWeight: isActive ? 700 : 500,
                  color: isActive ? 'var(--text-primary)' : 'var(--text-muted)',
                  background: isHovered && !isActive ? 'rgba(0,0,0,0.03)' : 'none',
                  border: 'none',
                  borderBottom: isActive ? '2px solid var(--text-primary)' : '2px solid transparent',
                  cursor: 'pointer',
                  display: 'flex',
                  alignItems: 'center',
                  gap: 6,
                  marginBottom: -1,
                  borderRadius: '6px 6px 0 0',
                  transition: 'all 0.15s',
                  fontFamily: 'inherit',
                }}
              >
                {tab.label}
                {count > 0 && (
                  <span style={{
                    fontSize: 10,
                    fontWeight: 600,
                    background: isActive ? 'var(--text-primary)' : 'var(--border)',
                    color: isActive ? '#fff' : 'var(--text-muted)',
                    borderRadius: 999,
                    padding: '1px 6px',
                    minWidth: 18,
                    textAlign: 'center',
                    transition: 'all 0.15s',
                  }}>
                    {count}
                  </span>
                )}
              </button>
            );
          })}
        </div>

        {/* Search */}
        <div style={{ position: 'relative', width: 240, flexShrink: 0, marginBottom: 8 }}>
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="var(--text-muted)" strokeWidth="2" strokeLinecap="round"
            style={{ position: 'absolute', left: 10, top: '50%', transform: 'translateY(-50%)' }}>
            <circle cx="11" cy="11" r="8" /><line x1="21" y1="21" x2="16.65" y2="16.65" />
          </svg>
          <input
            className="input-field"
            placeholder="Search orders..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            style={{ paddingLeft: 32, fontSize: 12, height: 34 }}
          />
        </div>
      </div>

      {/* Content */}
      {loading ? (
        <div style={{ display: 'flex', justifyContent: 'center', padding: '60px 0' }}>
          <div style={{ width: 24, height: 24, border: '3px solid var(--border)', borderTopColor: 'var(--gold)', borderRadius: '50%', animation: 'spin 0.6s linear infinite' }} />
        </div>
      ) : filteredOrders.length === 0 ? (
        <div style={{ textAlign: 'center', padding: '72px 0' }}>
          <div style={{
            width: 56, height: 56, borderRadius: 14, margin: '0 auto 18px',
            background: 'var(--bg-input)', border: '1px solid var(--border)',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
          }}>
            <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="var(--text-muted)" strokeWidth="1.6" strokeLinecap="round">
              <rect x="2" y="4" width="20" height="16" rx="2" /><path d="M7 15h0M2 9.5h20" />
            </svg>
          </div>
          <div style={{ fontSize: 16, fontWeight: 700, color: 'var(--text-primary)', marginBottom: 6 }}>
            {search.trim() ? 'No orders match your search' : 'No orders yet'}
          </div>
          <div style={{ fontSize: 13.5, color: 'var(--text-muted)', lineHeight: 1.5, maxWidth: 300, margin: '0 auto' }}>
            {search.trim() ? 'Try a different search term.' : 'Submit an order from a project cart to see it here.'}
          </div>
        </div>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
          {filteredOrders.map((order) => {
            const st = STATUS_CONFIG[order.status] ?? STATUS_CONFIG.draft;
            const isHovered = hoveredOrder === order.id;
            return (
              <div
                key={order.id}
                className="card"
                onMouseEnter={() => setHoveredOrder(order.id)}
                onMouseLeave={() => setHoveredOrder(null)}
                style={{
                  display: 'flex',
                  overflow: 'hidden',
                  transition: 'border-color 0.15s, box-shadow 0.15s',
                  borderColor: isHovered ? 'var(--border-strong)' : undefined,
                  boxShadow: isHovered ? '0 2px 8px rgba(0,0,0,0.06)' : undefined,
                }}
              >
                {/* Accent Bar */}
                <div style={{ width: 4, flexShrink: 0, background: st.accent, borderRadius: '8px 0 0 8px' }} />

                <div style={{ flex: 1, minWidth: 0 }}>
                  {/* Main row */}
                  <Link href={`/projects/${order.projectId}/orders/${order.id}`} style={{ textDecoration: 'none' }}>
                    <div style={{ padding: '14px 20px', display: 'flex', alignItems: 'center', gap: 14, cursor: 'pointer' }}>

                      {/* Status Icon */}
                      <div style={{
                        width: 38, height: 38, borderRadius: 10,
                        background: st.bg, border: `1px solid ${st.border}`,
                        display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0,
                      }}>
                        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke={st.color} strokeWidth="2" strokeLinecap="round">
                          <rect x="2" y="4" width="20" height="16" rx="2" /><path d="M7 15h0M2 9.5h20" />
                        </svg>
                      </div>

                      {/* Info */}
                      <div style={{ flex: 1, minWidth: 0 }}>
                        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                          <span style={{ fontSize: 13.5, fontWeight: 700, color: 'var(--text-primary)' }}>
                            #{order.id.slice(0, 8)}
                          </span>
                          <span style={{
                            fontSize: 10, fontWeight: 600,
                            background: st.bg, border: `1px solid ${st.border}`,
                            color: st.color, borderRadius: 999, padding: '1px 8px',
                          }}>
                            {st.label}
                          </span>
                        </div>
                        <div style={{ fontSize: 12, color: 'var(--text-muted)', marginTop: 3, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>
                          {order.project?.name || 'Unknown project'}
                          {order.project?.client?.name && <span style={{ opacity: 0.7 }}> &middot; {order.project.client.name}</span>}
                        </div>
                      </div>

                      {/* Meta chips */}
                      <div style={{ display: 'flex', alignItems: 'center', gap: 12, flexShrink: 0 }}>
                        <div style={{ textAlign: 'center' }}>
                          <div style={{ fontSize: 14, fontWeight: 700, color: 'var(--text-primary)' }}>{order._count.lineItems}</div>
                          <div style={{ fontSize: 10, color: 'var(--text-muted)', marginTop: 1 }}>items</div>
                        </div>
                        <div style={{ width: 1, height: 24, background: 'var(--border)' }} />
                        <div style={{ textAlign: 'center' }}>
                          <div style={{ fontSize: 14, fontWeight: 700, color: 'var(--text-primary)' }}>{order._count.brandPOs}</div>
                          <div style={{ fontSize: 10, color: 'var(--text-muted)', marginTop: 1 }}>brands</div>
                        </div>
                      </div>

                      {/* Date */}
                      <div style={{ fontSize: 11.5, color: 'var(--text-muted)', flexShrink: 0, width: 64, textAlign: 'right' }}>
                        {timeAgo(order.createdAt)}
                      </div>

                      {/* Total */}
                      <div style={{ fontSize: 16, fontWeight: 800, color: 'var(--text-primary)', flexShrink: 0, minWidth: 90, textAlign: 'right', letterSpacing: '-0.02em' }}>
                        {formatPrice(order.totalAmount)}
                      </div>

                      {/* Chevron */}
                      <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--text-muted)" strokeWidth="2" strokeLinecap="round" style={{
                        flexShrink: 0, opacity: isHovered ? 1 : 0.3, transition: 'opacity 0.15s, transform 0.15s',
                        transform: isHovered ? 'translateX(2px)' : 'none',
                      }}>
                        <polyline points="9 18 15 12 9 6" />
                      </svg>
                    </div>
                  </Link>

                  {/* Quick actions — only visible on hover */}
                  <div style={{
                    display: 'flex', gap: 6, padding: '0 20px 10px', paddingLeft: 72,
                    opacity: isHovered ? 1 : 0,
                    maxHeight: isHovered ? 40 : 0,
                    overflow: 'hidden',
                    transition: 'opacity 0.2s, max-height 0.2s',
                  }}>
                    <button
                      onClick={(e) => { e.preventDefault(); downloadInvoice(order); }}
                      style={{
                        display: 'flex', alignItems: 'center', gap: 5,
                        background: 'none', border: '1px solid var(--border)',
                        borderRadius: 6, padding: '3px 10px',
                        fontSize: 11, fontWeight: 600, color: 'var(--text-muted)',
                        cursor: 'pointer', fontFamily: 'inherit',
                        transition: 'all 0.12s',
                      }}
                      onMouseEnter={(e) => { e.currentTarget.style.borderColor = 'var(--border-strong)'; e.currentTarget.style.color = 'var(--text-primary)'; }}
                      onMouseLeave={(e) => { e.currentTarget.style.borderColor = 'var(--border)'; e.currentTarget.style.color = 'var(--text-muted)'; }}
                    >
                      <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round">
                        <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
                        <polyline points="7 10 12 15 17 10" />
                        <line x1="12" y1="15" x2="12" y2="3" />
                      </svg>
                      Invoice
                    </button>
                    <Link
                      href={`/projects/${order.projectId}/cart`}
                      onClick={(e) => e.stopPropagation()}
                      style={{
                        display: 'flex', alignItems: 'center', gap: 5,
                        background: 'none', border: '1px solid var(--border)',
                        borderRadius: 6, padding: '3px 10px',
                        fontSize: 11, fontWeight: 600, color: 'var(--text-muted)',
                        textDecoration: 'none',
                        transition: 'all 0.12s',
                      }}
                      onMouseEnter={(e) => { e.currentTarget.style.borderColor = 'var(--border-strong)'; e.currentTarget.style.color = 'var(--text-primary)'; }}
                      onMouseLeave={(e) => { e.currentTarget.style.borderColor = 'var(--border)'; e.currentTarget.style.color = 'var(--text-muted)'; }}
                    >
                      <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round">
                        <polyline points="17 1 21 5 17 9" />
                        <path d="M3 11V9a4 4 0 0 1 4-4h14" />
                      </svg>
                      Reorder
                    </Link>
                    {(order.status === 'paid' || order.status === 'split_to_brands' || order.status === 'closed') && (
                      <Link
                        href={`/projects/${order.projectId}/orders/${order.id}/tracking`}
                        onClick={(e) => e.stopPropagation()}
                        style={{
                          display: 'flex', alignItems: 'center', gap: 5,
                          background: 'none', border: '1px solid var(--green-border)',
                          borderRadius: 6, padding: '3px 10px',
                          fontSize: 11, fontWeight: 600, color: 'var(--green)',
                          textDecoration: 'none',
                          transition: 'all 0.12s',
                        }}
                        onMouseEnter={(e) => { e.currentTarget.style.background = 'var(--green-dim)'; }}
                        onMouseLeave={(e) => { e.currentTarget.style.background = 'none'; }}
                      >
                        <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round">
                          <polyline points="22 12 18 12 15 21 9 3 6 12 2 12" />
                        </svg>
                        Track
                      </Link>
                    )}
                    <Link
                      href={`/projects/${order.projectId}/orders/${order.id}`}
                      onClick={(e) => e.stopPropagation()}
                      style={{
                        display: 'flex', alignItems: 'center', gap: 5,
                        background: 'none', border: '1px solid var(--border)',
                        borderRadius: 6, padding: '3px 10px',
                        fontSize: 11, fontWeight: 600, color: 'var(--text-muted)',
                        textDecoration: 'none',
                        transition: 'all 0.12s',
                      }}
                      onMouseEnter={(e) => { e.currentTarget.style.borderColor = 'var(--border-strong)'; e.currentTarget.style.color = 'var(--text-primary)'; }}
                      onMouseLeave={(e) => { e.currentTarget.style.borderColor = 'var(--border)'; e.currentTarget.style.color = 'var(--text-muted)'; }}
                    >
                      <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round">
                        <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z" />
                        <circle cx="12" cy="12" r="3" />
                      </svg>
                      View Details
                    </Link>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
